export const QUIZZES = {
  en: [
    {
      text: "Eating or drinking in the lab is...",
      options: ["Allowed if careful", "Allowed near computers", "Not allowed", "Only for staff"],
      correctIndex: 2,
    },
    {
      text: "If clothing catches fire, you should:",
      options: ["Run to exit", "Stop, Drop, Roll", "Use water quickly", "Shake it off"],
      correctIndex: 1,
    },
    {
      text: "Which is correct for electrical safety?",
      options: ["Use damaged cords", "Overload outlets", "Keep liquids away", "Daisy-chain power strips"],
      correctIndex: 2,
    },
    {
      text: "PPE stands for:",
      options: ["Personal Protective Equipment", "Public Protection Effort", "Primary Power Equipment", "Personal Preferred Equipment"],
      correctIndex: 0,
    },
    {
      text: "Chemical waste should be:",
      options: ["Poured in sink", "Disposed in dedicated containers", "Left on bench", "Mixed with water"],
      correctIndex: 1,
    },
    {
      text: "PASS technique is for:",
      options: ["Fume hood", "First aid", "Fire extinguisher", "Eye wash"],
      correctIndex: 2,
    },
    {
      text: "When finished, equipment should be:",
      options: ["Left on", "Turned off", "Moved aside", "Covered with cloth"],
      correctIndex: 1,
    },
    {
      text: "You should work alone in the lab:",
      options: ["If experienced", "Never without permission", "At night is fine", "Anytime"],
      correctIndex: 1,
    },
    {
      text: "Labeling chemicals is:",
      options: ["Optional", "Required", "Only for acids", "Only for flammables"],
      correctIndex: 1,
    },
    {
      text: "Fume hood is used to:",
      options: ["Heat water", "Store tools", "Vent hazardous fumes", "Dry glassware"],
      correctIndex: 2,
    },
    {
      text: "In emergency you should:",
      options: ["Panic", "Call security / 112", "Hide", "Ignore"],
      correctIndex: 1,
    },
    {
      text: "Spilled chemical should be:",
      options: ["Wiped with bare hands", "Reported and handled per procedure", "Ignored", "Hosed down"],
      correctIndex: 1,
    },
    {
      text: "Never pipette by:",
      options: ["Pump", "Mouth", "Automatic pipette", "Bulb"],
      correctIndex: 1,
    },
    {
      text: "Keep aisles and exits:",
      options: ["Clear", "Used for storage", "Blocked temporarily", "Chairs only"],
      correctIndex: 0,
    },
    {
      text: "Use water on electrical fire?",
      options: ["Yes", "No", "If small", "If with sand"],
      correctIndex: 1,
    },
  ],

  ru: [
    {
      text: "Есть и пить в лаборатории...",
      options: ["Можно, если аккуратно", "Можно возле компьютеров", "Нельзя", "Только персоналу"],
      correctIndex: 2,
    },
    { text: "Если одежда загорелась, нужно:", options: ["Бежать к выходу", "Стоп, Лечь, Кувырок", "Быстро водой", "Стряхнуть"], correctIndex: 1 },
    { text: "Для электробезопасности верно:", options: ["Использовать поврежденные кабели", "Перегружать розетки", "Держать жидкости подальше", "«Гирлянды» из пилотов"], correctIndex: 2 },
    { text: "СИЗ означает:", options: ["Средства Индивидуальной Защиты", "Служба Инф. Защиты", "Система Инструм. Защиты", "Стандарт Инд. Защиты"], correctIndex: 0 },
    { text: "Химотходы следует:", options: ["Лить в раковину", "Выбрасывать в спецконтейнеры", "Оставлять на столе", "Разбавлять водой"], correctIndex: 1 },
    { text: "PASS — это техника для:", options: ["Вытяжного шкафа", "Доврачебной помощи", "Огнетушителя", "Глазной ванны"], correctIndex: 2 },
    { text: "По окончании работы оборудование:", options: ["Оставить включенным", "Выключить", "Сдвинуть в сторону", "Накрыть тканью"], correctIndex: 1 },
    { text: "Работать одному в лаборатории:", options: ["Если опытный — можно", "Нельзя без разрешения", "Ночью можно", "Всегда можно"], correctIndex: 1 },
    { text: "Маркировка реактивов:", options: ["Необязательна", "Обязательна", "Только для кислот", "Только для ЛВЖ"], correctIndex: 1 },
    { text: "Вытяжной шкаф используют для:", options: ["Нагрева воды", "Хранения инструментов", "Удаления вредных паров", "Сушки посуды"], correctIndex: 2 },
    { text: "При ЧС нужно:", options: ["Паниковать", "Звонить в охрану/112", "Прятаться", "Игнорировать"], correctIndex: 1 },
    { text: "Пролитый реактив следует:", options: ["Вытирать руками", "Сообщить и убрать по регламенту", "Игнорировать", "Смыть шлангом"], correctIndex: 1 },
    { text: "Никогда не пипетировать:", options: ["Грушей", "Ртом", "Автопипеткой", "Насосом"], correctIndex: 1 },
    { text: "Проходы и выходы должны быть:", options: ["Свободны", "Складом", "Временно загорожены", "Только стулья"], correctIndex: 0 },
    { text: "Поливать водой электрический пожар?", options: ["Да", "Нет", "Если маленький", "Если с песком"], correctIndex: 1 },
  ],

  fr: [
    { text: "Manger/boire au labo est...", options: ["Autorisé si prudent", "Autorisé près des PC", "Interdit", "Réservé au personnel"], correctIndex: 2 },
    { text: "Si les vêtements prennent feu :", options: ["Courir vers la sortie", "Stop, Drop, Roll", "Vite de l'eau", "Secouer"], correctIndex: 1 },
    { text: "Pour l'électricité :", options: ["Câbles abîmés", "Surcharger les prises", "Éloigner les liquides", "Chaîner des multiprises"], correctIndex: 2 },
    { text: "EPI signifie :", options: ["Équipement de Protection Individuelle", "Effort Public d'Intervention", "Énergie Puissance Industrielle", "Équipement Préféré Individuel"], correctIndex: 0 },
    { text: "Déchets chimiques :", options: ["Dans l'évier", "Conteneurs dédiés", "Sur la paillasse", "Diluer à l'eau"], correctIndex: 1 },
    { text: "PASS concerne :", options: ["Sorbonne", "Premiers secours", "Extincteur", "Lave-œil"], correctIndex: 2 },
    { text: "Après usage, le matériel :", options: ["Rester allumé", "Être éteint", "Être déplacé", "Être couvert"], correctIndex: 1 },
    { text: "Travailler seul au labo :", options: ["Si expérimenté", "Jamais sans autorisation", "La nuit ok", "Toujours"], correctIndex: 1 },
    { text: "Étiquetage des produits :", options: ["Optionnel", "Obligatoire", "Seulement acides", "Seulement inflammables"], correctIndex: 1 },
    { text: "La hotte sert à :", options: ["Chauffer l'eau", "Ranger", "Évacuer les vapeurs", "Sécher"], correctIndex: 2 },
    { text: "En urgence :", options: ["Paniquer", "Appeler sécurité/112", "Se cacher", "Ignorer"], correctIndex: 1 },
    { text: "Produit renversé :", options: ["Essuyer à mains nues", "Signaler et traiter", "Ignorer", "Rincer au tuyau"], correctIndex: 1 },
    { text: "Ne jamais pipeter :", options: ["Poire", "Avec la bouche", "Pipette auto", "Pompe"], correctIndex: 1 },
    { text: "Allées et sorties :", options: ["Dégagées", "Stockage", "Bloquées", "Chaises uniquement"], correctIndex: 0 },
    { text: "Eau sur feu électrique ?", options: ["Oui", "Non", "Si petit", "Avec sable"], correctIndex: 1 },
  ],

  ky: [
    { text: "Лабораторияда жеп-ичүү...", options: ["Этият болсо болот", "Компьютер жанында болот", "Болбойт", "Персоналга гана"], correctIndex: 2 },
    { text: "Кийим күйсө эмне кылуу керек:", options: ["Эшикке чуркоо", "Токто, Жат, Домала", "Тез суу куюу", "Силкүү"], correctIndex: 1 },
    { text: "Электр коопсуздугу үчүн туурасы:", options: ["Бузук зым колдонуу", "Розетканы ашыкча жүктөө", "Суюктукту алыстатуу", "Пилотторду чынжыр кылуу"], correctIndex: 2 },
    { text: "ЖЖК деген эмне:", options: ["Жеке коргонуу каражаттары", "Жалпы коргоо иши", "Жогорку кубат жабдыгы", "Жеке тандалма жабдык"], correctIndex: 0 },
    { text: "Химиялык калдыктар:", options: ["Жуунучуго куюлат", "Атайын идишке салышат", "Столго калтырышат", "Суу менен аралаштырышат"], correctIndex: 1 },
    { text: "PASS техникасы:", options: ["Вытяжка", "Биринчи жардам", "Өрт өчүргүч", "Көз жуугуч"], correctIndex: 2 },
    { text: "Бүтсө жабдуу:", options: ["Калсын күйүп", "Өчүрүлөт", "Жанга жылат", "Токмоктолот"], correctIndex: 1 },
    { text: "Лабораторияда жалгыз иштөө:", options: ["Тажрыйбалуу болсо болот", "Уруксатсыз болбойт", "Түндө болот", "Ар убак"], correctIndex: 1 },
    { text: "Заттарды белгилөө:", options: ["Мажбур эмес", "Милдеттүү", "Кычкылдарга гана", "Жанарларга гана"], correctIndex: 1 },
    { text: "Вытяжка эмне үчүн:", options: ["Суу ысытуу", "Курал сактоо", "Зыяны бууларды чыгаруу", "Кургатуу"], correctIndex: 2 },
    { text: "ЧС маалында:", options: ["Паника", "Коопсуздукка/112 чалуу", "Жашынуу", "Көңүл бурбоо"], correctIndex: 1 },
    { text: "Төгүлгөн зат:", options: ["Кол менен аарчуу", "Эреже боюнча жыйноо", "Көрмөксөн болуу", "Шланг менен жууш"], correctIndex: 1 },
    { text: "Эч качан пипетка кылбаңыз:", options: ["Груша менен", "Ооз менен", "Автопипетка", "Насос"], correctIndex: 1 },
    { text: "Өткөөл/чыгуулар:", options: ["Бош", "Кампа", "Блоктолгон", "Стулдар гана"], correctIndex: 0 },
    { text: "Электр өртүнө суу?", options: ["Ооба", "Жок", "Кичине болсо", "Кум менен"], correctIndex: 1 },
  ],
};
