export const translations = {
  en: {
    appTitle: "Safety Rules in IT Labs",
    nav: {
      home: "Home",
      notice: "Reminder",
      quiz: "Quiz",
      leaderboard: "Leaderboard",
      login: "Login",
      register: "Register",
      profile: "Profile",
      logout: "Logout",
    },
    home: {
      title: "Lab Safety & Fire Safety",
      subtitle: "Read the reminder, pass the quiz, and get your score.",
      ctaReminder: "Read Reminder",
      ctaQuiz: "Start Quiz",
    },
    notice: {
      title: "Safety Reminder",
      sections: {
        general: "General Conduct",
        fire: "Fire Safety",
        electrical: "Electrical & Equipment",
        chemical: "Chemicals & PPE",
        emergency: "Emergency Response",
      },
      rules: {
        general: [
          "No eating or drinking in the lab.",
          "Keep aisles and exits clear.",
          "Do not work alone without permission.",
          "Report unsafe conditions immediately.",
          "Know the location of exits and safety equipment.",
        ],
        fire: [
          "Keep flammable materials away from ignition sources.",
          "Do not block fire extinguishers or fire alarms.",
          "Know PASS: Pull, Aim, Squeeze, Sweep.",
          "If clothing catches fire: Stop, Drop, Roll.",
          "Never use water on electrical or oil fires.",
        ],
        electrical: [
          "Inspect cords and plugs for damage before use.",
          "Do not overload outlets or use daisy chains.",
          "Turn off equipment when not in use.",
          "Keep liquids away from electrical devices.",
          "Use only approved extension cords.",
        ],
        chemical: [
          "Always wear appropriate PPE (goggles, lab coat, gloves).",
          "Label and store chemicals properly.",
          "Never pipette by mouth.",
          "Use fume hoods when required.",
          "Dispose of waste in designated containers.",
        ],
        emergency: [
          "Call campus security or emergency services immediately.",
          "Provide exact location and nature of incident.",
          "Evacuate calmly and assemble at the meeting point.",
          "Assist those in need if it is safe to do so.",
          "Follow staff instructions at all times.",
        ],
      },
    },
    quiz: {
      title: "Safety Quiz",
      start: "Start",
      question: "Question",
      timeLeft: "Time left",
      seconds: "sec",
      correct: "Correct! +10 points",
      wrong: "Incorrect.",
      final: "Your total score",
      alreadyTook: (score) => `Congratulations! You scored ${score} points!`,
      needLogin: "Please log in with your university email first.",
    },
    auth: {
      title: "Login / Register",
      name: "Name",
      email: "Email",
      loginBtn: "Login",
      registerBtn: "Register",
      uniOnly: "Use your university email (@alatoo.edu.kg)",
      welcome: "Welcome",
      loggedIn: "Successfully logged in",
      loggedOut: "Logged out",
    },
    leaderboard: {
      title: "Leaderboard",
      name: "Name",
      score: "Score",
      date: "Date",
      empty: "No results yet.",
    },
    profile: {
      title: "Profile",
      name: "Name",
      email: "Email",
      score: "Total Score",
      attempt: "Attempt",
      yes: "Completed",
      no: "Not yet",
    },
    footer: {
      authors: "Authors",
      coauthors: "Co-authors",
    },
    langs: { en: "English", ru: "Русский", fr: "Français", ky: "Кыргызча" },
  },

  ru: {
    appTitle: "Правила безопасности в IT-лабораториях",
    nav: {
      home: "Главная",
      notice: "Памятка",
      quiz: "Вопросник",
      leaderboard: "Рейтинг",
      login: "Вход",
      register: "Регистрация",
      profile: "Профиль",
      logout: "Выйти",
    },
    home: {
      title: "Пожарная и лабораторная безопасность",
      subtitle: "Изучи памятку, пройди тест и получи баллы.",
      ctaReminder: "Открыть памятку",
      ctaQuiz: "Начать тест",
    },
    notice: {
      title: "Памятка по безопасности",
      sections: {
        general: "Общие правила поведения",
        fire: "Пожарная безопасность",
        electrical: "Электробезопасность и оборудование",
        chemical: "Химия и СИЗ",
        emergency: "Действия при ЧС",
      },
      rules: {
        general: [
          "Не есть и не пить в лаборатории.",
          "Держите проходы и выходы свободными.",
          "Не работайте в одиночку без разрешения.",
          "Немедленно сообщайте об опасных ситуациях.",
          "Знайте расположение выходов и средств безопасности.",
        ],
        fire: [
          "Держите горючие материалы подальше от источников огня.",
          "Не загромождайте огнетушители и пожарные извещатели.",
          "Помните PASS: Pull, Aim, Squeeze, Sweep.",
          "Если одежда загорелась: Стоп, Лечь, Кувырок.",
          "Нельзя тушить водой электрические/масляные пожары.",
        ],
        electrical: [
          "Проверяйте кабели и вилки перед использованием.",
          "Не перегружайте розетки, не делайте «гирлянду».",
          "Выключайте оборудование, когда не используете.",
          "Держите жидкости подальше от электроприборов.",
          "Используйте только одобренные удлинители.",
        ],
        chemical: [
          "Всегда носите СИЗ (очки, халат, перчатки).",
          "Подписывайте и правильно храните реактивы.",
          "Никогда не пипетируйте ртом.",
          "Работайте в вытяжном шкафу при необходимости.",
          "Утилизируйте отходы в спец. контейнеры.",
        ],
        emergency: [
          "Немедленно звоните в охрану кампуса или 112.",
          "Сообщите точное место и характер происшествия.",
          "Эвакуируйтесь спокойно, собирайтесь на точке сбора.",
          "Помогайте, если это безопасно.",
          "Всегда выполняйте указания персонала.",
        ],
      },
    },
    quiz: {
      title: "Тест по безопасности",
      start: "Начать",
      question: "Вопрос",
      timeLeft: "Осталось",
      seconds: "сек",
      correct: "Верно! +10 баллов",
      wrong: "Неверно.",
      final: "Ваш общий результат",
      alreadyTook: (score) => `Поздравляем! У вас ${score} баллов!`,
      needLogin: "Сначала войдите с университетской почтой.",
    },
    auth: {
      title: "Вход / Регистрация",
      name: "Имя",
      email: "Почта",
      loginBtn: "Войти",
      registerBtn: "Зарегистрироваться",
      uniOnly: "Войдите с университетской почты (@alatoo.edu.kg)",
      welcome: "Добро пожаловать",
      loggedIn: "Вы успешно вошли",
      loggedOut: "Вы вышли",
    },
    leaderboard: {
      title: "Рейтинг",
      name: "Имя",
      score: "Баллы",
      date: "Дата",
      empty: "Пока нет результатов.",
    },
    profile: {
      title: "Профиль",
      name: "Имя",
      email: "Почта",
      score: "Баллы всего",
      attempt: "Попытка",
      yes: "Пройдено",
      no: "Еще нет",
    },
    footer: { authors: "Авторы", coauthors: "Соавторы" },
    langs: { en: "English", ru: "Русский", fr: "Français", ky: "Кыргызча" },
  },

  fr: {
    appTitle: "Règles de sécurité dans les IT labos",
    nav: {
      home: "Accueil",
      notice: "Mémo",
      quiz: "Quiz",
      leaderboard: "Classement",
      login: "Connexion",
      register: "Inscription",
      profile: "Profil",
      logout: "Déconnexion",
    },
    home: {
      title: "Sécurité incendie et de laboratoire",
      subtitle: "Lisez le mémo, passez le quiz et obtenez votre score.",
      ctaReminder: "Lire le mémo",
      ctaQuiz: "Commencer le quiz",
    },
    notice: {
      title: "Mémo de sécurité",
      sections: {
        general: "Conduite générale",
        fire: "Sécurité incendie",
        electrical: "Électrique & Équipement",
        chemical: "Produits chimiques & EPI",
        emergency: "Urgences",
      },
      rules: {
        general: [
          "Ne pas manger ni boire dans le labo.",
          "Gardez les allées et sorties dégagées.",
          "Ne travaillez pas seul sans autorisation.",
          "Signalez immédiatement toute situation dangereuse.",
          "Connaissez les sorties et équipements de sécurité.",
        ],
        fire: [
          "Éloignez les matières inflammables des sources d'ignition.",
          "Ne bloquez pas les extincteurs ou alarmes incendie.",
          "Retenez PASS : Pull, Aim, Squeeze, Sweep.",
          "Si les vêtements prennent feu : Stop, Drop, Roll.",
          "N'utilisez jamais d'eau sur un feu électrique/huile.",
        ],
        electrical: [
          "Vérifiez câbles et fiches avant usage.",
          "N’encombrez pas les prises et évitez les multiprises en chaîne.",
          "Éteignez le matériel après usage.",
          "Éloignez les liquides des appareils.",
          "Utilisez uniquement des rallonges homologuées.",
        ],
        chemical: [
          "Portez toujours les EPI (lunettes, blouse, gants).",
          "Étiquetez et stockez correctement les produits.",
          "Ne pipetez jamais avec la bouche.",
          "Utilisez les hottes si nécessaire.",
          "Éliminez les déchets dans les conteneurs dédiés.",
        ],
        emergency: [
          "Appelez immédiatement la sécurité du campus ou les secours.",
          "Donnez le lieu exact et la nature de l’incident.",
          "Évacuez calmement vers le point de rassemblement.",
          "Aidez si c’est sans danger.",
          "Suivez les instructions du personnel.",
        ],
      },
    },
    quiz: {
      title: "Quiz de sécurité",
      start: "Commencer",
      question: "Question",
      timeLeft: "Temps restant",
      seconds: "s",
      correct: "Correct ! +10 points",
      wrong: "Faux.",
      final: "Votre score total",
      alreadyTook: (score) => `Félicitations! Vous avez gagné ${score} points!`,
      needLogin: "Veuillez d'abord vous connecter avec l’email universitaire.",
    },
    auth: {
      title: "Connexion / Inscription",
      name: "Nom",
      email: "Email",
      loginBtn: "Se connecter",
      registerBtn: "S'inscrire",
      uniOnly: "Utilisez l'email universitaire (@alatoo.edu.kg)",
      welcome: "Bienvenue",
      loggedIn: "Connecté avec succès",
      loggedOut: "Déconnecté",
    },
    leaderboard: {
      title: "Classement",
      name: "Nom",
      score: "Score",
      date: "Date",
      empty: "Pas encore de résultats.",
    },
    profile: {
      title: "Profil",
      name: "Nom",
      email: "Email",
      score: "Score total",
      attempt: "Tentative",
      yes: "Effectué",
      no: "Pas encore",
    },
    footer: { authors: "Auteurs", coauthors: "Co-auteurs" },
    langs: { en: "English", ru: "Русский", fr: "Français", ky: "Кыргызча" },
  },

  ky: {
    appTitle: "IT лабораторияларындагы коопсуздук эрежелери",
    nav: {
      home: "Башкы бет",
      notice: "Эскертме",
      quiz: "Тест",
      leaderboard: "Рейтинг",
      login: "Кирүү",
      register: "Катталуу",
      profile: "Профиль",
      logout: "Чыгуу",
    },
    home: {
      title: "Өрт жана лаборатория коопсуздугу",
      subtitle: "Эскертмени окуп, тесттен өтүп, балл алыңыз.",
      ctaReminder: "Эскертмени ачуу",
      ctaQuiz: "Тестти баштоо",
    },
    notice: {
      title: "Коопсуздук эскертмеси",
      sections: {
        general: "Жалпы тартип",
        fire: "Өрт коопсуздугу",
        electrical: "Электр жана жабдуулар",
        chemical: "Химия жана ЖЖК",
        emergency: "Өзгөчө кырдаал",
      },
      rules: {
        general: [
          "Лабораторияда тамак жебеңиз/ичпеңиз.",
          "Өткөөлдөр менен чыгуулар бош болсун.",
          "Уруксатсыз жалгыз иштебеңиз.",
          "Кооптуу жагдайды дароо кабарлаңыз.",
          "Чыгууларды жана коопсуздук шаймандарын билиңиз.",
        ],
        fire: [
          "Жанучу материалдарды от булактарынан алыстатыңыз.",
          "Өрт өчүргүчтөрдү/сигналдарды тоспоңуз.",
          "PASS эсиңизде болсун: Pull, Aim, Squeeze, Sweep.",
          "Кийим күйсө: Токто, Жат, Домала.",
          "Электр/май күйүүсүнө суу колдонбоңуз.",
        ],
        electrical: [
          "Зымдарды жана вилкасын текшериңиз.",
          "Розеткаларды ашыкча жүктөбөңүз.",
          "Колдонбогондо жабдууну өчүрүңүз.",
          "Суюктукту жабдуудан алыс кармаңыз.",
          "Тек текшерилген узарткычтарды колдонуңуз.",
        ],
        chemical: [
          "Ар дайым ЖЖК кийиңиз (көз айнек, халат, мээлей).",
          "Заттарды туура белгелеңиз жана сактаңыз.",
          "Ооз менен пипетка кылбаңыз.",
          "Керек болсо соргуч шкаф колдонуңуз.",
          "Калдыктарды атайын идишке таштаңыз.",
        ],
        emergency: [
          "Дароо кампус коопсуздугуна же 112ге чалыңыз.",
          "Так жайды жана окуянын түрүн айтыңыз.",
          "Тынч эвакуация болуп, чогулуу жерге барыңыз.",
          "Коопсуз болсо жардам бериңиз.",
          "Ар дайым персоналдын көрсөтмөсүн аткарыңыз.",
        ],
      },
    },
    quiz: {
      title: "Коопсуздук тести",
      start: "Баштоо",
      question: "Суроо",
      timeLeft: "Калған убакыт",
      seconds: "сек",
      correct: "Туура! +10 балл",
      wrong: "Туура эмес.",
      final: "Жалпы баллыңыз",
      alreadyTook: (score) => `Куттуктайбыз! Сизде ${score} упай бар!`,
      needLogin: "Адегенде университеттик почта менен кириңиз.",
    },
    auth: {
      title: "Кирүү / Катталуу",
      name: "Атыңыз",
      email: "Почта",
      loginBtn: "Кирүү",
      registerBtn: "Катталуу",
      uniOnly: "Университет почтасын колдонуңуз (@alatoo.edu.kg)",
      welcome: "Кош келиңиз",
      loggedIn: "Ийгиликтүү кирдиңиз",
      loggedOut: "Чыктыңыз",
    },
    leaderboard: {
      title: "Рейтинг",
      name: "Аты",
      score: "Баллы",
      date: "Дата",
      empty: "Азырынча жыйынтык жок.",
    },
    profile: {
      title: "Профиль",
      name: "Аты",
      email: "Почта",
      score: "Жалпы балл",
      attempt: "Аткаруу",
      yes: "Өткөн",
      no: "Азырынча жок",
    },
    footer: { authors: "Авторлор", coauthors: "Соавторлор" },
    langs: { en: "English", ru: "Русский", fr: "Français", ky: "Кыргызча" },
  },
};
